# Generated by Django 6.1.1 on 2026-09-11 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('question_type', models.CharField(choices=[('TEXT', 'Text'), ('SINGLE_CHOICE', 'Single Choice'), ('MULTIPLE_CHOICE', 'Multiple Choice'), ('SCALE', 'Scale')], max_length=20)),
                ('weight', models.PositiveIntegerField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='reviews.reviewperiod')),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='reviews.question')),
            ],
            options={
                'ordering': ('display_order', 'id'),
            },
        ),
    ]
