# Generated by Django 6.1.1 on 2026-09-11 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('reviews', '0003_review_answer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('individual_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('department_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('department_adjustment', models.DecimalField(decimal_places=2, max_digits=5)),
                ('final_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_score', to='reviews.review')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='department_performances', to='departments.department')),
                ('review_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_performances', to='reviews.reviewperiod')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('review_period', 'department'), name='unique_department_performance_per_period')],
            },
        ),
    ]
